### ISSUE TITLE
IMAP Connection Issues

### ISSUE THREAD

**Issue by titanism** [forwardemail/status.forwardemail.net#1172]
We are investigating reports of connection issues to our IMAP/POP3 servers.  As soon as we have an update we will post here.

**Comment by extremeleadprogram** [comment]
Still seeing issues here:

![image](https://github.com/user-attachments/assets/c770114d-69c3-44f9-a6a4-7c3c9cc8b3ca)

**Comment by extremeleadprogram** [comment]
![image](https://github.com/user-attachments/assets/e47adcb6-392e-4688-856a-aad91ac701e2)

**Comment by btonbadger** [comment]
Hi,

Appreciate you're fighting fires with this one, but is there any update please? I'm desperately trying to see if the lack of emails in my forwardmail imap account is down to the sqlite issues and continuing timeouts or something more sinister?

Cheers

BtonBadger

**Comment by extremeleadprogram** [comment]
@btonbadger - I'm with you and if that is any indication, I think it's this issue mostly if I had to guess.

**Comment by extremeleadprogram** [comment]
@titanism - any updates... seems worse now than ever... ???
