### ISSUE TITLE
Optimizing MX server performance

### ISSUE THREAD

**Issue by titanism** [forwardemail/status.forwardemail.net#1319]
We are actively mitigating a spam attack on both our MX servers and Stripe customer checkout payment pages.  We will keep this issue open in the interim.  Thank you for your patience 🙏

**Comment by tp199303** [comment]
Is this the reason why that I cannot receive the emails sent from microsoft, outlook and hotmail to my own domain which is using forwardemail services?

**Comment by vitalii-work** [comment]
@tp199303 you're not alone. I can't  receive verification emails from Google.

**Comment by tp199303** [comment]
> @tp199303 you're not alone. I can't receive verification emails from Google.

My domain on forwardemails.net can receive emails from Google, but cannot from Microsoft.

**Comment by vitalii-work** [comment]
@titanism, yes, I've received them with 5-10 min delays.

**Comment by junxit** [comment]
Out of curiosity, is it known if the MX servers are particularly targeted, or domains that happen to be routed via the MX servers?
