### ISSUE TITLE
Investigating email forwarding delays

### ISSUE THREAD

**Issue by titanism** [forwardemail/status.forwardemail.net#695]
Since approximately 2 PM CT there have been intermittent delays with email forwarding.  We are investigating and will follow up ASAP with resolution.

**Comment by paulstenhouse** [comment]
Are there known issues with email sending too? I have emails queued up.

**Comment by jgrahamc** [comment]
This is John Graham-Cumming, Cloudflare CTO. Can someone from Forward Email drop me an email (jgc@cloudflare.com) so I can see what was going on?

**Comment by rommycf** [comment]
hi @titanism please let us know if you're still seeing this issue. We would need more information to start the investigation. Thanks in advance!
